name: Simple Android Build

on:
  workflow_dispatch: # Manual trigger only for testing
  
jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y android-sdk
        echo "ANDROID_HOME=/usr/lib/android-sdk" >> $GITHUB_ENV
        echo "/usr/lib/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "/usr/lib/android-sdk/platform-tools" >> $GITHUB_PATH
    
    - name: Install npm dependencies
      working-directory: ./first-draft-implementation
      run: npm install
    
    - name: Build web project
      working-directory: ./first-draft-implementation
      run: npm run build
    
    - name: Sync Capacitor project
      working-directory: ./first-draft-implementation
      run: npx cap sync android
    
    - name: Make gradlew executable
      run: chmod +x first-draft-implementation/android/gradlew
    
    - name: Build debug APK
      working-directory: first-draft-implementation/android
      run: ./gradlew assembleDebug --stacktrace
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: tower-defense-apk
        path: first-draft-implementation/android/app/build/outputs/apk/debug/*.apk